# YOLOv8 Exit Sign Detection Model Configuration
model_info:
  name: 'exit_detection_yolov8n'
  version: '1.0.0'
  type: 'object_detection'
  framework: 'YOLOv8'
  classes: ['exit', 'lit_exit_sign', 'unlit_exit_sign']
  input_size: [640, 640]
  confidence_threshold: 0.5
  iou_threshold: 0.45
  trained_on: 'UUM Exit Sign Dataset'
  
safety_assessment:
  minimum_exit_signs: 2
  weights:
    lit_exit_sign: 1.0
    unlit_exit_sign: 0.3
    exit: 0.7
  thresholds:
    safe: 0.8
    caution: 0.5
    unsafe: 0.0
    
deployment:
  platforms: ['Android', 'iOS']
  inference_time: '~100ms'
  model_size: '6.2MB'
  accuracy: 'mAP50: 0.85+'
